dataset: coco
expname: coco-100-seeds-64
num_workers: 8
model:
  hidden_size: 96
train:
  batch_size: 128
  runs: 4
  lr_patience: 50
  epochs: 200
metis:
  n_patches: 64
pos_enc:
  lap_dim: 8
  rw_dim: 0